# Generated by Django 4.0.6 on 2022-08-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_number',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
