# Generated by Django 4.0.6 on 2022-08-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_patient_patient_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(default='male', max_length=30),
            preserve_default=False,
        ),
    ]
